apiVersion: v1
kind: Secret
metadata:
  name: employee-service-secret
  namespace: employee-prod
  labels:
    app.kubernetes.io/name: employee-service
type: Opaque
stringData:
  database-password: "sa"
  jwt-secret: "REPLACE_IN_PRODUCTION"
  external-api-key: "REPLACE_IN_PRODUCTION"